version: '3'
services:
  cypress:
    image: docker-registry.production.smartbox.com/cypress/included:13.10.0
    volumes:
      - .:/e2e
    entrypoint: []
    working_dir: /e2e
    command: ["sh", "-c",  "tail -f /dev/null"]
    environment:
      - DISPLAY=host.docker.internal:0.0
    network_mode: "host"